function controlsFor(t,step){let f=ENGINE_FAMILY[t.engine];if(step===0)return `<h4>Keşif modu</h4><div class="control-row"><span>Animasyon</span><input data-control="speed" type="range" min="1" max="5" value="3"><b data-value="speed">3×</b></div>`;let labels={motion:'Kuvvet',energy:'Enerji',thermal:'Sıcaklık',pressure:'Basınç',circuit:'Gerilim',wave:'Frekans',optics:'Açı',trig:'Açı',graph:'Parametre',probability:'Deneme',data:'Veri',particles:'Tanecik',gas:'Hacim',acidbase:'pH',equilibrium:'Denge',population:'Nüfus',climate:'Sıcaklık'};return `<h4>Manipülasyon paneli</h4><div class="control-row"><span>${labels[f]||'Parametre'}</span><input data-control="main" type="range" min="0" max="100" value="50"><b data-value="main">50</b></div><div class="control-row"><span>Destek</span><input data-control="support" type="range" min="0" max="100" value="${Math.max(10,80-step*15)}"><b data-value="support">${Math.max(10,80-step*15)}%</b></div>`}
function wireControls(t){$$('[data-control]').forEach(i=>i.oninput=()=>{let target=$(`[data-value="${i.dataset.control}"]`);if(target)target.textContent=i.value+(i.dataset.control==='support'?'%':'');let stage=$('#visualStage');if(i.dataset.control==='main')stage.style.filter=`hue-rotate(${(Number(i.value)-50)*.5}deg) brightness(${.8+Number(i.value)/250})`;if(i.dataset.control==='speed')stage.style.setProperty('--speed',`${6-Number(i.value)}s`)})}
function challengeFor(t,step){let prompts=['Sahnedeki ana ilişki nedir?','Parametreyi artırınca ne değişti?','Animasyonu durdursak sıradaki durum ne olur?','Bu konunun sınav sorusunda ilk kontrol edeceğin şey nedir?','Bu ilişkiyi farklı bir problemde nasıl kullanırsın?'];let opts=optionsFor(t,step);return `<small>AKTİF KONTROL · ${['KEŞFET','MANİPÜLE ET','TAHMİN','UYGULA','TRANSFER'][step]}</small><h4>${prompts[step]}</h4><div class="challenge-options">${opts.map((x,i)=>`<button data-answer="${i}">${String.fromCharCode(65+i)} · ${x}</button>`).join('')}</div>`}
function optionsFor(t,step){let f=ENGINE_FAMILY[t.engine];let good={text:'Metindeki kanıt ilişkisini izlemek',tokens:'Yapının cümledeki görevini kontrol etmek',graph:'Değişkenler arasındaki ilişkiyi grafikten okumak',math:'İşlemi temsil üzerinden kurmak',geometry:'Değişmeyen geometrik ilişkiyi belirlemek',motion:'Kuvvet-hareket yönünü önce kavramsal tahmin etmek',particles:'Makro olayı tanecik düzeyiyle açıklamak',cell:'Yapı ile işlevi birlikte düşünmek',timeline:'Olayı önce-sonra ve neden-sonuç içinde konumlandırmak',map:'Mekânsal dağılışı süreçle ilişkilendirmek',argument:'İddia ile onu destekleyen gerekçeyi ayırmak',literature:'Dönem, tür ve sanatçı ilişkisini zaman içinde konumlandırmak',language:'Cümle içi bağlam ve gramer ipuçlarını birlikte kullanmak'}[f]||'Kavram ile sonucu neden-sonuç içinde bağlamak';return [good,'Yalnız ezberlenen anahtar kelimeyi aramak','Animasyondaki rengi doğru cevap kabul etmek','Bağlamı atlayıp sonuca doğrudan gitmek']}
function explainFor(t,step){let verbs=['Bu aşamada amaç cevabı ezberlemek değil, konunun yapısını görmektir.','Şimdi tek bir parametreyi değiştirip diğerlerinin tepkisini izliyorsun.','Tahmin aşaması, formül veya tanımdan önce zihinsel modelini test eder.','Uygulama aşaması görsel modeli sınav tipi karara dönüştürür.','Transfer aşaması aynı kavramı yeni bağlamda tanımayı öğretir.'];return `${t.title} · ${verbs[step]}`}
function gradeProgress(t,ok){let p=state.progress[t.id]||{attempts:0,correct:0,mastery:.25};p.attempts++;if(ok)p.correct++;p.mastery=Math.min(.98,Math.max(.08,p.mastery+(ok?.09:-.04)));state.progress[t.id]=p;save()}
function bindChallenge(){$$('[data-answer]').forEach(b=>b.onclick=()=>{let t=topicById(state.topicId),ok=Number(b.dataset.answer)===0;$$('[data-answer]').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');if(!ok)$('[data-answer="0"]').classList.add('correct');gradeProgress(t,ok)})}
function renderMap(){let total=DATA.topicCount,done=Object.keys(state.progress).length;$('#mapSummary').textContent=`${DATA.courses.length} ders · ${DATA.unitCount} ünite · ${total} konu · ${done} konuda öğrenci verisi.`;$('#mapList').innerHTML=DATA.courses.map(c=>`<div class="generic-card" style="border-left:3px solid ${c.accent}"><b>${c.name}</b><span>${c.units.length} ünite · ${c.units.reduce((a,u)=>a+u.topics.length,0)} konu · ${c.testGroup}</span></div>`).join('')}
$('#backCatalog').onclick=()=>showScreen('catalog');$('#backCourse').onclick=()=>{renderCourse();showScreen('course')};$('#prevStep').onclick=()=>{if(state.step>0){state.step--;renderLesson();bindChallenge()}};$('#nextStep').onclick=()=>{if(state.step<4){state.step++;renderLesson();bindChallenge()}else{gradeProgress(topicById(state.topicId),true);renderCourse();showScreen('course')}};$('#searchInput').oninput=renderCatalog;$('#clearSearch').onclick=()=>{$('#searchInput').value='';renderCatalog()};$$('.bottom-nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.nav));
const obs=new MutationObserver(()=>{if(state.screen==='lesson')bindChallenge()});obs.observe($('#challengeCard'),{childList:true});renderCatalog();showScreen('catalog');
